apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment1
  namespace: my-first-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        image: nginx
        imagePullPolicy: Always
        name: container1
        resources:
          limits:
            cpu: 500m
            memory: 768Mi
          requests:
            cpu: 300m
            memory: 512Mi
      restartPolicy: Always